Add missing #include <memory>
Fixes:

    In file included from .../src/MoveToFront.cpp:1:0:
    .../src/MoveToFront.h: In static member function ‘static void bw::MoveToFront::encode(std::istream&, std::ostream&)’:
    .../src/MoveToFront.h:30:29: error: ‘shared_ptr’ is not a member of ‘std’